export type ProviderName='local'|'openrouter'|'gemini'|'custom';
export type Mode='image'|'video';
export interface GenerationRequest{prompt:string;mode:Mode;width?:number;height?:number;steps?:number;cfg?:number;seed?:number;}
export interface GenerationResult{provider:ProviderName;status:'ready'|'queued'|'fallback'|'error';text?:string;assetUrl?:string;warning?:string;jobId?:string;}
export interface ChatMessage{role:'system'|'user'|'assistant';content:string}
const env=()=>(import.meta as ImportMeta & {env:Record<string,string|undefined>}).env;
const keyFor=(p:string)=>env()[`VITE_${p.toUpperCase()}_API_KEY`]??'';
const endpointFor=(p:string,m:Mode)=>env()[`VITE_${p.toUpperCase()}_${m.toUpperCase()}_ENDPOINT`]??env()[`VITE_${p.toUpperCase()}_ENDPOINT`]??'';
async function parse(response:Response,p:ProviderName,m:Mode):Promise<GenerationResult>{const raw=await response.text();let d:any={};try{d=JSON.parse(raw)}catch{};const url=d.url??d.assetUrl??d.output?.url??d.output?.[0]?.url??d.data?.[0]?.url??d.images?.[0]?.url??d.video?.url;const job=d.id??d.jobId??d.task_id;return {provider:p,status:m==='video'&&!url?'queued':'ready',assetUrl:url,jobId:job,text:d.text??d.message,warning:url||job?undefined:'Provider returned no media URL'}}
async function post(p:ProviderName,r:GenerationRequest):Promise<GenerationResult>{const key=keyFor(p);const endpoint=endpointFor(p,r.mode);if(!key||!endpoint)return {provider:p,status:'error',warning:`${p} ${r.mode} endpoint is not configured.`};const headers:Record<string,string>={'Content-Type':'application/json','Authorization':`Bearer ${key}`};if(p==='openrouter'){headers['HTTP-Referer']=location.origin;headers['X-Title']='Grok Girls'};const url=p==='gemini'?`${endpoint}${endpoint.includes('?')?'&':'?'}key=${encodeURIComponent(key)}`:endpoint;const model=env()[`VITE_${p.toUpperCase()}_${r.mode.toUpperCase()}_MODEL`]??env()[`VITE_${p.toUpperCase()}_MODEL`];const body={prompt:r.prompt,model,width:r.width,height:r.height,steps:r.steps,cfg:r.cfg,seed:r.seed};const response=await fetch(url,{method:'POST',headers:p==='gemini'?{'Content-Type':'application/json'}:headers,body:JSON.stringify(body)});if(!response.ok)throw new Error(`${p} HTTP ${response.status}`);return parse(response,p,r.mode)}
class Local{readonly name='local' as const;available(){return true}async generate(r:GenerationRequest):Promise<GenerationResult>{return {provider:'local',status:'fallback',text:`Local ${r.mode} adapter active. Configure a local HTTP ${r.mode} endpoint for real media.`}}}
class Cloud{constructor(public readonly name:Exclude<ProviderName,'local'>){}available(){return Boolean(keyFor(this.name)&&(endpointFor(this.name,'image')||endpointFor(this.name,'video')))}async generate(r:GenerationRequest){return post(this.name,r)}}
export function providers(){return [new Local(),new Cloud('openrouter'),new Cloud('gemini'),new Cloud('custom')]}
export async function generateWithFallback(r:GenerationRequest,preferred:ProviderName='local'):Promise<GenerationResult>{const all=providers();for(const p of [...all.filter(x=>x.name===preferred),...all.filter(x=>x.name!==preferred)]){if(!p.available()&&p.name!=='local')continue;try{const out=await p.generate(r);if(out.status==='ready'||out.status==='queued'||p.name==='local')return out}catch(e){if(p.name===preferred)return {provider:p.name,status:'error',warning:e instanceof Error?e.message:'Generation failed'}}}return {provider:'local',status:'fallback',warning:'No configured generation provider.'}}
export async function chatWithProvider(messages:ChatMessage[],preferred:ProviderName='openrouter'){const e=env();if(preferred==='local')return {provider:'local' as const,text:'Local companion mode is active.'};if(preferred==='openrouter'){const key=e.VITE_OPENROUTER_API_KEY??'';if(!key)return {provider:'openrouter' as const,text:'OpenRouter is not configured.',warning:'Set VITE_OPENROUTER_API_KEY.'};const endpoint=e.VITE_OPENROUTER_CHAT_ENDPOINT??'https://openrouter.ai/api/v1/chat/completions';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`,'HTTP-Referer':location.origin,'X-Title':'Grok Girls'},body:JSON.stringify({model:e.VITE_OPENROUTER_CHAT_MODEL??'openai/gpt-4o-mini',messages})});if(!r.ok)throw new Error(`OpenRouter HTTP ${r.status}`);const d=await r.json();return {provider:'openrouter' as const,text:d.choices?.[0]?.message?.content??'No response.'}}
if(preferred==='gemini'){const key=e.VITE_GEMINI_API_KEY??'';if(!key)return {provider:'gemini' as const,text:'Gemini is not configured.',warning:'Set VITE_GEMINI_API_KEY.'};const model=e.VITE_GEMINI_CHAT_MODEL??'gemini-2.5-flash';const endpoint=e.VITE_GEMINI_CHAT_ENDPOINT??`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;const contents=messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const system=messages.find(m=>m.role==='system')?.content;const r=await fetch(`${endpoint}?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:system?{parts:[{text:system}]}:undefined,contents})});if(!r.ok)throw new Error(`Gemini HTTP ${r.status}`);const d=await r.json();return {provider:'gemini' as const,text:d.candidates?.[0]?.content?.parts?.map((p:any)=>p.text).join('')??'No response.'}}
const key=e.VITE_CUSTOM_AI_KEY??'';const endpoint=e.VITE_CUSTOM_CHAT_ENDPOINT??'';if(!key||!endpoint)return {provider:'custom' as const,text:'Custom provider is not configured.'};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:e.VITE_CUSTOM_CHAT_MODEL,messages})});if(!r.ok)throw new Error(`Custom HTTP ${r.status}`);const d=await r.json();return {provider:'custom' as const,text:d.choices?.[0]?.message?.content??d.text??'No response.'}}
