import React,{useMemo,useState} from 'react';
import {Girl,Mode,rooms,seedGirls,Room} from './models/studio';
import {advanceStory,initialStory,StoryState,storyPrompt} from './models/story';
import {addMemory,buildGenerationPrompt,loadGirls,saveGirls} from './services/memory';
import {AvatarState,interactionState,loadAvatarState,saveAvatarState,statePrompt} from './services/avatarState';
import {addGalleryItem} from './services/gallery';
import {generateWithFallback} from './services/providers';
import {ChatMessage,loadChat,localReply,saveChat} from './services/chat';
import './styles.css';

export default function App(){
 const [girls,setGirls]=useState<Girl[]>(()=>loadGirls(seedGirls));
 const [selectedId,setSelectedId]=useState(girls[0].id); const [mode,setMode]=useState<Mode>('image'); const [prompt,setPrompt]=useState(''); const [enhanced,setEnhanced]=useState(true); const [roomId,setRoomId]=useState(rooms[0].id); const [interactionId,setInteractionId]=useState(''); const [provider,setProvider]=useState('local'); const [result,setResult]=useState(''); const [chatInput,setChatInput]=useState(''); const [chat,setChat]=useState<ChatMessage[]>(()=>loadChat(girls[0].id));
 const girl=useMemo(()=>girls.find(g=>g.id===selectedId)!,[girls,selectedId]); const room:Room=useMemo(()=>rooms.find(r=>r.id===roomId)??rooms[0],[roomId]);
 const [avatarState,setAvatarState]=useState<AvatarState>(()=>loadAvatarState(girls[0].id,girls[0])); const [story,setStory]=useState<StoryState>(()=>initialStory(girls[0].affinity/25));
 const selectGirl=(id:string)=>{const g=girls.find(x=>x.id===id)!;setSelectedId(id);setChat(loadChat(id));setAvatarState(loadAvatarState(id,g));setStory(initialStory(g.affinity/25))};
 const interact=()=>{const next=interactionState(avatarState);setAvatarState(next);saveAvatarState(girl.id,next);const level=Math.floor(Math.min(next.affection,next.trust)/25);setStory(s=>advanceStory(s,level));const nextGirls=girls.map(g=>g.id===girl.id?{...g,affinity:next.affection,trust:next.trust,emotion:next.emotion}:g);setGirls(nextGirls);saveGirls(nextGirls)};
 const generate=async()=>{interact();const nextState=interactionState(avatarState);const nextStory=advanceStory(story,Math.floor(Math.min(nextState.affection,nextState.trust)/25));const full=buildGenerationPrompt(girl,room,prompt,mode,enhanced,interactionId,nextState,nextStory);setResult('Preparing generation…');const r=await generateWithFallback({prompt:full,mode,width:mode==='image'?768:1280,height:mode==='image'?768:720},provider as any);setResult(`${r.text??'Generation request accepted.'}${r.assetUrl?`\n\nAsset: ${r.assetUrl}`:''}${r.warning?`\n\n${r.warning}`:''}`);addGalleryItem({avatarId:girl.id,mode,prompt:full,assetUrl:r.assetUrl,provider:r.provider});const next=addMemory(girls,girl.id,`${mode} generation in ${room.name}`,prompt||'showcase scene',room.id);setGirls(next);saveGirls(next)};
 const sendChat=()=>{if(!chatInput.trim())return;interact();const now=Date.now();const next=[...chat,{id:String(now),role:'user' as const,text:chatInput,createdAt:now},{id:String(now+1),role:'assistant' as const,text:localReply(girl,room,chatInput),createdAt:now+1}];setChat(next);saveChat(girl.id,next);setChatInput('');};
 return <main><header><div><span className="eyebrow">GROK GIRLS</span><h1>Character Studio</h1><p>Persona • Memory • Avatar • Story • Scenes • Generation • Chat</p></div><div className="status">● LOCAL-FIRST</div></header>
 <section className="layout"><aside><h2>Characters</h2>{girls.map(g=><button className={g.id===selectedId?'girl active':'girl'} onClick={()=>selectGirl(g.id)} key={g.id}><span className="avatar">{g.name[0]}</span><span><b>{g.name}</b><small>{g.room} · {Math.round(g.affinity)}% bond</small></span></button>)}<div className="sideblock"><b>Provider</b><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="local">Local fallback</option><option value="openrouter">OpenRouter</option><option value="gemini">Gemini</option><option value="custom">Custom endpoint</option></select></div></aside>
 <section className="studio"><div className="hero"><div className="orb">{girl.name[0]}</div><div><span className="eyebrow">ACTIVE PERSONA</span><h2>{girl.name}</h2><p>{girl.bio}</p><div className="chips">{girl.traits.map(t=><span key={t}>{t}</span>)}</div><div className="stats"><span>Bond {Math.round(avatarState.affection)}%</span><span>Trust {Math.round(avatarState.trust)}%</span><span>Mood {girl.emotion}</span><span>Chapter {story.chapter}</span></div></div></div>
 <div className="controls"><div className="grid2"><label>Room<select value={roomId} onChange={e=>setRoomId(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Interaction<select value={interactionId} onChange={e=>setInteractionId(e.target.value)}><option value="">Default</option>{room.interactions.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label></div><label>Scene prompt<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the scene, wardrobe, mood, camera or story..."/></label><div className="row"><button className={mode==='image'?'selected':''} onClick={()=>setMode('image')}>IMAGE</button><button className={mode==='video'?'selected':''} onClick={()=>setMode('video')}>VIDEO</button><button className={enhanced?'selected':''} onClick={()=>setEnhanced(v=>!v)}>ENHANCE</button><button onClick={interact}>INTERACT</button><button className="generate" onClick={generate}>GENERATE</button></div></div>
 <article className="result"><span className="eyebrow">STORY ENGINE</span><p>{storyPrompt(story)}</p><small>{statePrompt(avatarState)}</small></article>
 {result&&<article className="result"><span className="eyebrow">GENERATION PIPELINE</span><p>{result}</p></article>}
 <div className="lower"><div className="memory"><h3>Memory matrix</h3>{girl.memories.length?<ul>{girl.memories.slice(0,6).map(m=><li key={m.id}>{m.summary}{m.detail?` · ${m.detail}`:''}</li>)}</ul>:<p>No memories yet.</p>}</div><div className="memory"><h3>Companion chat</h3><div className="chatlog">{chat.slice(-5).map(m=><div className={m.role} key={m.id}><b>{m.role==='user'?'You':girl.name}</b><span>{m.text}</span></div>)}</div><div className="chatrow"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Talk to the active persona…"/><button onClick={sendChat}>SEND</button></div></div></div>
 </section></section></main>
}
